<?xml version="1.0" encoding="utf-8"?><Database Name="BirdanismanSite" Class="DbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Tblcustomer" Member="Tblcustomer">
    <Type Name="Tblcustomer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AdSoyad" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SirketAdi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Mesaj" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Tarih" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>